import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TokenExpiredModalWrapper } from "./components/session/sessionManager";
import ContextProvider from "./context/contextProvider";
import { ErrorBoundary } from "react-error-boundary";
import FallbackErrorBoundary from "./components/error/FallbackErrorBoundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IPhone House Varela",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <ErrorBoundary FallbackComponent={FallbackErrorBoundary}>

          <TokenExpiredModalWrapper />
          {children}
          </ErrorBoundary>
        </ContextProvider>
      </body>
    </html>
  );
}
