import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TokenExpiredModalWrapper  from "@/components/session/SessionManager";
import ContextProvider from "@/context/contextProvider";
import SideNav from "@/components/nav/SideNav";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IPhone House Varela",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const allCookies = cookies(); 
  const hasCookies = allCookies.get('__iphonehouse_varela__'); 
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
            <TokenExpiredModalWrapper />
            <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
              <SideNav />
              <div className={hasCookies ? "flex-grow p-3 md:overflow-y-auto" : "flex-grow md:overflow-y-auto"}>
                {children}
              </div>
            </div>
        </ContextProvider>
      </body>
    </html>
  );
}
